### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jpeg729** [osm3000/sequence_generation_pytorch#1]
I started learning pytorch using this repo which was a great help to getting started. Thanks.

Now, I would like to publish my own repo of code bits concentrating on time-series prediction, but some parts of my code are still based on yours and this repo has no license. In theory therefore I have no right to use your code in my project.

Would you mind [choosing a license](https://choosealicense.com/)? The MIT license is the most permissive, it is the one that I would like to use.

**Comment by osm3000** [comment]
Thank you for taking note of this issue. I've just created MIT license based on your suggestion. Please feel free to use the code anyway you like.
Cheers, Omar

**Comment by jpeg729** [comment]
Thank you for the quick and generous reply!

If you are interested my repo is online [here](https://github.com/jpeg729/pytorch-bits/).
